### ISSUE TITLE
contains() to be replaced with includes()

### ISSUE THREAD

**Issue by zubayrali** [chhoumann/DemoVault#1]
```dataviewjs
const pages = dv.current().file.inlinks.where(p => dv.page(p.path).tags?.contains('project'));

dv.table(["Project", "Status"], pages.map(p => {
	const page = dv.page(p.path); 
	return [page.file.link, page.status]
}));
```

is not working for me, it throws **Evaluation Error: TypeError: dv.page(...).tags?.contains is not a function** , I replaced it `includes()` and it seems to be working now, I also read that `contains()` is deprecated. I'd be happy to make a PR.

Big thanks for this workflow btw.

**Comment by chhoumann** [comment]
Hi @zubayrrr

Thank you! I've made the replacement and pushed it to the vault :)
