### ISSUE TITLE
Error on Projects Dashboard: TypeError: Failed to set the 'max' property on 'HTMLProgressElement': The provided double value is non-finite

### ISSUE THREAD

**Issue by prashant2402** [chhoumann/DemoVault#10]
Thanks Christian, for publishing your vault, much appreciated!

I see this error when I create a new project using QuickAdd. Looks like the view is incorrectly set on the `project_item_template` as when I change `progress-bar` to `total-progress-bar` in setting `Bar` variable it works just fine:

``` 
Dataview: Error while executing view 'views/progress-bar/view.js'.

TypeError: Failed to set the 'max' property on 'HTMLProgressElement': The provided double value is non-finite.
```

![image](https://user-images.githubusercontent.com/1729202/220446248-f07668b5-0c4f-4b77-8c38-67c3d297b704.png)

**Comment by chhoumann** [comment]
Hi @prashant2402 

Thank you for reporting this! Seems I didn't catch that I had added bars to projects. This wasn't actually originally intended (in the first iteration), but was added with auto-tracking.

You are right that the solution is to use `total-progress-bar`, as that tracks by tasks, and not YAML properties.
I have updated the template with this script:
``````
```js quickadd
const shouldProjectTrackProgress = await this.quickAddApi.yesNoPrompt(`Should this project track progress via markdown tasks?`, 'Enabling this will give the project note a Bar property, similarly to auto-tracked goals. The tasks are auto-tracked, so each time you check one off, you make progress.');
if (shouldProjectTrackProgress) return "Bar:: `$= dv.view('total-progress-bar', {file: '; {{VALUE:⚒ Add Project}}'})`";
```
``````

Replacing `Bar` with that in the template will prompt users to whether they want to use this feature or not. :)

Thanks!
