### ISSUE TITLE
Are auto tracking Goals not compatible with the dashboard?

### ISSUE THREAD

**Issue by jccastro94** [chhoumann/DemoVault#11]
Goals are at 100% but they are still tracked. When I try to see what the Progress and Target values are, they are literal text. I should be getting "3" on both target and progress (which happens with I add the whole script in with dataviewjs). 

Is auto tracking not compatible with the dashboard? Or is my inline dataview not grabbing the Progress and Target scripts like it's supposed to?

![image](https://user-images.githubusercontent.com/73132288/221475062-b88b5c5e-d115-47ba-a21a-2984605d91de.png)
![image](https://user-images.githubusercontent.com/73132288/221475190-f9e43df2-c781-46b1-b74d-abdd4dba1c3c.png)

**Comment by jccastro94** [comment]
Tested it with this DemoVault and it seems it will keep tracking a Goal despite it being finished. Any thoughts on how I could fix? if not, all good. Thanks for all your work in the Obsidian Community!

![image](https://user-images.githubusercontent.com/73132288/221476642-f36fc8bf-3bb7-422d-9e29-45b3764e3d14.png)

**Comment by chhoumann** [comment]
Hey @jccastro94 

Can't believe I didn't catch that. Thank you for reporting it!

Need to convert the progress & targets to numbers, otherwise Dataview gets confused.
Here's the updated goals query:
``````
```dataview
TABLE WITHOUT ID
	(link(file.path, alias)) as title,
	Bar
FROM #goal
WHERE number(Progress) != number(Target)
SORT Type DESC
```
``````

You can see the difference here:
``````diff
```dataview
TABLE WITHOUT ID
	(link(file.path, alias)) as title,
	Bar
FROM #goal
+ WHERE number(Progress) != number(Target)
- WHERE Progress != Target
SORT Type DESC
```
``````

**Comment by PeterBeckley** [comment]
Any new auto-tracked goals created in the demo vault are not showing up with the dashboard goal table query as is. Regardless of level of completion. If I remove the WHERE then all of them show up in addition to all existing goals from the default vault. I've tried this before and after updating the theme/plug-ins, adding no new ones.
