### ISSUE TITLE
Progress bar issue

### ISSUE THREAD

**Issue by ForeGuards** [chhoumann/DemoVault#13]
Hi,

I'm getting this error, once I set the progress to a number on my goals:

```Dataview: Error while executing view 'views/progress-bar/view.js'.

TypeError: Failed to set the 'max' property on 'HTMLProgressElement': The provided double value is `non-finite`.
``` 
Any idea where the issue is?

Thank you for your support!

**Comment by ForeGuards** [comment]
I misunderstood the meaning of the target and progress...

**Comment by chhoumann** [comment]
Just want to check in - everything works now?

**Comment by ForeGuards** [comment]
Yes, my target value was lower than my progress value, that was the issue.

**Comment by ForeGuards** [comment]
I actually have something different and I found out it is in the theme. In your minimal theme I see the goals in the cards, but once I change the theme I see it like a list.... did you change something in your minimal theme?

This is how I see the goals with all other themes:
<img width="1455" alt="CleanShot 2023-06-27 at 08 57 44@2x" src="https://github.com/chhoumann/DemoVault/assets/35286609/8d33d2ea-608e-4717-8d54-1f700c13a9bb">

**Comment by chhoumann** [comment]
Simply using the latest version of Minimal works for me. I haven't really modified it.

## Minimal theme settings
![image](https://github.com/chhoumann/DemoVault/assets/29108628/8f4341be-cc09-4f16-ae8d-29d7f944da18)
![image](https://github.com/chhoumann/DemoVault/assets/29108628/55686ece-1f88-465f-a78c-655c07124713)
![image](https://github.com/chhoumann/DemoVault/assets/29108628/f9c623b7-6c7c-4969-9b11-982934fe024c)

## Style settings
### Minimal
```json
{
  "minimal-style@@h1-size": "2em",
  "minimal-style@@h2-size": "1.6em",
  "minimal-style@@h3-size": "1.37em",
  "minimal-style@@h4-size": "1.25em",
  "minimal-style@@h5-size": "1.12em",
  "minimal-style@@h6-size": "1.12em"
}
```

### Minimal Cards
```json
{}
```

### Minimal Mobile
```json
{}
```

### Minimal Advanced Settings
```json
{}
```
