### ISSUE TITLE
Progress Bar broken with Dataview 0.5.34

### ISSUE THREAD

**Issue by AwkwardSandwich** [chhoumann/DemoVault#3]
Hello,

When downloading the DemoVault and upgrading Dataview to the 0.5.34 version, the progress bars only display \<HTMLDivElement\>.

![image](https://user-images.githubusercontent.com/2075525/173233493-b66c1655-2f41-48d3-a9ca-08654a395226.png)

Thank you!

**Comment by MrDuderino2U** [comment]
I was trying to adapt the dashboard as I think it is so cool, but was running into this issue on my personal vault. Three hours later after trying to even copy the exact templates and quick add setup removing mine, it was still not working I found this. I verified it by updating this vault's dataview plug-in and the above error is present.

**Comment by MrDuderino2U** [comment]
Just a quick comment, it is impacted with Dataview 0.5.33 as well.

**Comment by n3rdbuddy** [comment]
Modify the last line in view.js from 
`dv.paragraph(containerEl)` 
to
`dv.paragraph(containerEl.innerHTML)`

**Comment by MrDuderino2U** [comment]
That fixed it, thank you!!

**Comment by n3rdbuddy** [comment]
> Modify the last line in view.js from `dv.paragraph(containerEl)` to `dv.paragraph(containerEl.innerHTML)`

I'd be happy to make a PR if that's a thing... :)

**Comment by chhoumann** [comment]
Hi!

Thank you for raising this. I've never had the issue, which is pretty odd. But using `innerHTML` doesn't break the system, so I've pushed an update to the main branch where views use `innerHTML`. Then we're sure compatibility is 👍
