### ISSUE TITLE
Could "Progress" be refreshing automated ？

### ISSUE THREAD

**Issue by wnse** [chhoumann/DemoVault#7]
It should be better if the goal progress(number) could update automated when kanban changed each time.

**Comment by Keloran** [comment]
this is in my pull request https://github.com/chhoumann/DemoVault/pull/8

**Comment by chhoumann** [comment]
I've previously added auto tracking to the system, which was on a separate branch. @Keloran has taken the time to improve this.

It's now part of the main branch, so you can use the 'auto-track feature'. :)
